[header]
text = """
SPDX-License-Identifier: Apache-2.0
Copyright 2026 The OCX Authors"""

[files]
includes = [
    "*.cmake",
    "CMakeLists.txt",
    "tests/**/*.cmake",
    "tests/**/CMakeLists.txt",
    "examples/**/CMakeLists.txt",
    "scripts/**/*.py",
]
excludes = ["build/**"]
