#:schema https://grimoire.rs/schemas/grimoire-config.schema.json
[options]
clients = ["claude", "codex"]

[bundles]
cmake-essentials = "ghcr.io/ocx-sh/lore/cmake-essentials:latest"
code-docs-essentials = "ghcr.io/ocx-sh/lore/code-docs-essentials:latest"
docs-essentials = "ghcr.io/ocx-sh/lore/docs-essentials:latest"

[skills]

[rules]
