[tools]
actionlint = "ocx.sh/actionlint/actionlint:latest"
asciinema = "ocx.sh/asciinema/asciinema:3.2"
cmake = "ocx.sh/kitware/cmake:3.31"
git-cliff = "ocx.sh/git-cliff/git-cliff:latest"
go-task = "ocx.sh/go-task/task:latest"
hawkeye = "ocx.sh/hawkeye/hawkeye:latest"
lychee = "ocx.sh/lychee/lychee:latest"
ninja = "ocx.sh/ninja-build/ninja:latest"
uv = "ocx.sh/astral-sh/uv:latest"
node = "ocx.sh/nodejs/node:24"
pnpm = "ocx.sh/pnpm/pnpm:11"
