[tools]
actionlint = "ocx.sh/actionlint:latest"
cmake = "ocx.sh/cmake:3.31"
git-cliff = "ocx.sh/git-cliff:latest"
go-task = "ocx.sh/go-task:latest"
hawkeye = "ocx.sh/hawkeye:latest"
lychee = "ocx.sh/lychee:latest"
ninja = "ocx.sh/ninja:latest"
uv = "ocx.sh/uv:latest"
