#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The OCX Authors

"""Refreshes the dist.json snapshot embedded in ocx.cmake.

Fetches https://setup.ocx.sh/dist.json (or --source <file|url>), validates
it against the pinned ocx version in ocx.cmake (8 release targets, sha256
well-formed), and splices it between the snapshot markers. Never bumps
__OCX_PIN_VERSION - that is a deliberate, separate change.
"""

import argparse
import json
import pathlib
import re
import sys
import urllib.request

DEFAULT_URL = "https://setup.ocx.sh/dist.json"
BEGIN = "# --- BEGIN OCX DIST SNAPSHOT (generated by scripts/update_dist.py - do not edit) ---"
END = "# --- END OCX DIST SNAPSHOT ---"
TARGETS_PER_VERSION = 8


def load(source: str) -> str:
    if re.match(r"^https?://", source):
        with urllib.request.urlopen(source) as resp:  # noqa: S310 - explicit source
            return resp.read().decode("utf-8")
    return pathlib.Path(source).read_text(encoding="utf-8")


def validate(raw: str, pin: str) -> None:
    manifest = json.loads(raw)
    assert manifest.get("schema") == 1, f"unsupported dist.json schema {manifest.get('schema')}"
    rows = [r for r in manifest["releases"] if r["version"] == pin]
    assert len(rows) == TARGETS_PER_VERSION, (
        f"expected {TARGETS_PER_VERSION} targets for pinned ocx {pin}, got {len(rows)}"
    )
    for row in rows:
        assert re.fullmatch(r"[0-9a-f]{64}", row["sha256"]), f"malformed sha256 in {row}"
    assert "]=]" not in raw, "dist.json would terminate the CMake bracket literal"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default=DEFAULT_URL, help="manifest file or URL")
    parser.add_argument(
        "--ocx-cmake",
        default=pathlib.Path(__file__).resolve().parent.parent / "ocx.cmake",
        type=pathlib.Path,
    )
    parser.add_argument("--check", action="store_true", help="validate only, do not rewrite")
    args = parser.parse_args()

    text = args.ocx_cmake.read_text(encoding="utf-8")
    pin_match = re.search(r'set\(__OCX_PIN_VERSION "([^"]+)"\)', text)
    assert pin_match, "no __OCX_PIN_VERSION in ocx.cmake"
    pin = pin_match.group(1)

    begin = text.index(BEGIN)
    end = text.index(END)
    assert begin < end, "snapshot markers out of order"

    if args.check:
        embedded = re.search(r"set\(__OCX_DIST_JSON \[=\[\n(.*)\]=\]\)", text, re.DOTALL)
        assert embedded, "no embedded snapshot found"
        validate(embedded.group(1), pin)
        print(f"ok: embedded snapshot covers pinned ocx {pin}")
        return 0

    raw = load(str(args.source)).strip() + "\n"
    validate(raw, pin)
    block = f"{BEGIN}\nset(__OCX_DIST_JSON [=[\n{raw}]=])\n"
    args.ocx_cmake.write_text(text[:begin] + block + text[end:], encoding="utf-8")
    print(f"updated {args.ocx_cmake} from {args.source} (pinned ocx {pin})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
