#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The OCX Authors

"""Bump find_ocx to an ocx CLI release: snapshot, pin and CI pins in lockstep.

Moves the dist.json snapshot in ocx.cmake, __OCX_PIN_VERSION and every
ocx-sh/setup-ocx `version:` pin in .github/workflows together, or none of them.
--check (task dist:check) validates the committed files offline.
"""

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path
from urllib.parse import unquote, urlsplit

DIST_URL = "https://setup.ocx.sh/dist.json"
EXPECTED_TARGETS = 8
# file(ARCHIVE_EXTRACT) in ocx_bootstrap() handles all three.
KNOWN_EXTS = (".zip", ".tar.gz", ".tar.xz")
# ocx_bootstrap() downloads row["url"] verbatim (unless a mirror rewrites it),
# so these are all that stands between a fabricated row and an
# attacker-chosen host.
ARTIFACT_HOST = "github.com"
ARTIFACT_PATH = "/ocx-sh/ocx/releases/download/"
ARTIFACT_PREFIX = f"https://{ARTIFACT_HOST}{ARTIFACT_PATH}"
# One url path segment: no separator, no dot-segment spelling, no space.
SEGMENT = r"[A-Za-z0-9._+-]+"
SEGMENT_RE = re.compile(SEGMENT)
# The shape a release asset url has: <tag>/<filename>, one segment each.
ARTIFACT_PATH_RE = re.compile(re.escape(ARTIFACT_PATH) + f"{SEGMENT}/{SEGMENT}")
RELEASE_PAGE = "https://github.com/ocx-sh/ocx/releases"
SHA256_RE = re.compile(r"[0-9a-f]{64}")

REPO = Path(__file__).resolve().parents[1]
OCX_CMAKE = REPO / "ocx.cmake"
WORKFLOWS = REPO / ".github" / "workflows"

BEGIN = "# --- BEGIN OCX DIST SNAPSHOT (generated by scripts/update_dist.py - do not edit) ---"
END = "# --- END OCX DIST SNAPSHOT ---"
PIN_RE = re.compile(r'(set\(__OCX_PIN_VERSION ")([^"]+)("\))')
SNAPSHOT_RE = re.compile(r"set\(__OCX_DIST_JSON \[=\[\n(.*)\]=\]\)\n", re.DOTALL)


def die(msg):
    sys.exit(f"error: {msg}")


def ext_of(filename):
    if not isinstance(filename, str):
        return None
    for e in KNOWN_EXTS:
        if filename.endswith(e):
            return e
    return None


def on_release_host(u):
    """True only for a URL that really resolves to the ocx release host."""
    # An allowlist on the path shape: blocklists of separators are an open
    # set, and github.com normalises "/../" and "\\" server-side, so a prefix
    # match alone serves another repository's asset under a forged row's sha256.
    # urlsplit() lstrips WHATWG C0-or-space, so a leading control character
    # would be dropped before any check below sees it and stay in the url.
    if not isinstance(u, str) or not (u.isascii() and u.isprintable()) or " " in u:
        return False
    try:
        p = urlsplit(u)
    except ValueError:  # e.g. a malformed IPv6 literal
        return False
    # startswith() runs on the raw path (refuses "download%2fv1/x"); the
    # dot-segment check runs on the decoded one (refuses "download/../x").
    path = unquote(p.path)
    return bool(
        p.scheme == "https"
        and p.netloc == ARTIFACT_HOST  # netloc, not hostname: userinfo must not pass
        and not p.query
        and not p.fragment
        and p.path.startswith(ARTIFACT_PATH)
        and ARTIFACT_PATH_RE.fullmatch(path)
        and ".." not in path.split("/")
    )


def version_key(v):
    """Parses "x.y.z" into an integer tuple; die()s on anything that is not
    ASCII dotted-decimal. isdigit() is not the check: it accepts superscripts
    (raw ValueError) and isdecimal() alone accepts Arabic-Indic digits.
    """
    if not isinstance(v, str) or not all(p.isascii() and p.isdecimal() for p in v.split(".")):
        die(f"{v!r} is not a dotted-numeric version (e.g. '0.6.5')")
    return tuple(int(p) for p in v.split("."))


def read(path):
    return Path(path).read_bytes().decode("utf-8")


def write(path, text):
    Path(path).write_bytes(text.encode("utf-8"))


def pin_of(text):
    m = PIN_RE.search(text)
    if not m:
        die(f"set(__OCX_PIN_VERSION \"...\") not found in {OCX_CMAKE}")
    return m.group(2)


def snapshot_span(text):
    """(start, end) offsets of the snapshot block: BEGIN line through END line."""
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        die(f"{OCX_CMAKE} must carry exactly one BEGIN and one END OCX DIST SNAPSHOT marker")
    begin, end = text.index(BEGIN), text.index(END)
    if begin > end:
        die("snapshot markers out of order")
    return begin, end


def embedded_snapshot(text):
    begin, end = snapshot_span(text)
    m = SNAPSHOT_RE.fullmatch(text[begin + len(BEGIN) + 1 : end])
    if not m:
        die(f"no `set(__OCX_DIST_JSON [=[ ... ]=])` block between the markers in {OCX_CMAKE}")
    try:
        return json.loads(m.group(1))
    except json.JSONDecodeError as e:
        die(
            f"the embedded snapshot in {OCX_CMAKE} is not valid JSON ({e}) - restore it with "
            f"`git checkout -- {OCX_CMAKE}`, then re-run"
        )


def splice_snapshot(text, body):
    """Replaces the snapshot block with `body` (the fetched bytes, verbatim:
    re-serialising would make the one diff that matters, a changed sha256,
    unreadable)."""
    raw = body.decode("utf-8").strip() + "\n"
    if "]=]" in raw:
        die("dist.json would terminate the CMake bracket literal")
    begin, end = snapshot_span(text)
    block = f"{BEGIN}\nset(__OCX_DIST_JSON [=[\n{raw}]=])\n"
    return text[:begin] + block + text[end:]


def set_pin(text, version):
    return PIN_RE.sub(rf"\g<1>{version}\g<3>", text, count=1)


def fetch_snapshot():
    """Fetches and parses the upstream manifest; writes nothing. Returns
    (body, manifest): the raw bytes for the caller to splice and the parsed
    dict for the caller to validate. The write happens last, only once every
    guard passes.
    """
    # setup.ocx.sh 403s the default Python-urllib agent; identify ourselves.
    req = urllib.request.Request(DIST_URL, headers={"User-Agent": "find-ocx-update-dist"})
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            body = r.read()
    except Exception as e:  # noqa: BLE001 - report any network/HTTP failure the same way
        die(f"could not fetch {DIST_URL}: {e}")
    try:
        manifest = json.loads(body)
    except json.JSONDecodeError as e:
        die(f"{DIST_URL} returned invalid JSON: {e}")
    return body, manifest


def newest_stable(manifest):
    latest = (manifest.get("latest") or {}).get("version")
    if latest:
        return latest
    stable = [r["version"] for r in manifest["releases"] if r.get("channel") == "stable"]
    if not stable:
        die("snapshot has no stable releases and no 'latest' field")
    return max(stable, key=version_key)


def rows_for(manifest, version):
    return [r for r in manifest["releases"] if r["version"] == version]


def check_row(r, where):
    """Dies on one row that would break ocx_bootstrap() or point it at bytes
    nobody vouched for: channel stable, 64-hex sha256, release-host url,
    single-segment tag and filename, extractable extension.

    The sha256 column is the trust root of ocx_bootstrap(). Fields are read
    with .get() so a malformed row dies with an actionable message, not a
    KeyError.
    """
    if r.get("channel") != "stable":
        die(
            f"{where}: channel is {r.get('channel', '<missing>')!r}, not 'stable' - "
            f"find_ocx ships stable ocx releases only. Wait for the stable release, "
            f"or name an older stable with --version <x.y.z>."
        )
    if not isinstance(r.get("sha256"), str) or not SHA256_RE.fullmatch(r["sha256"]):
        die(
            f"{where}: sha256 is {r.get('sha256')!r}, not 64 lowercase hex chars - "
            f"that value is what ocx_bootstrap() enforces. Check {DIST_URL} "
            f"against {RELEASE_PAGE} before shipping this row."
        )
    if not on_release_host(r.get("url")):
        die(
            f"{where}: url {r.get('url')!r} does not resolve to {ARTIFACT_PREFIX} - "
            f"ocx_bootstrap() uses it verbatim, and a prefix match is no defence "
            f"(github.com normalises '..' server-side). Mirrors belong in "
            f"OCX_INSTALL_MIRROR_URL; if the release host really moved, change "
            f"ARTIFACT_HOST/ARTIFACT_PATH in this script deliberately."
        )
    # The mirror url is <mirror>/<tag>/<filename>, so both are path segments
    # in their own right; one `..` walks a level out of the release directory.
    for field in ("tag", "filename"):
        value = r.get(field)
        if not isinstance(value, str) or not SEGMENT_RE.fullmatch(value) or value in (".", ".."):
            die(
                f"{where}: {field} is {value!r}, which is not a single path segment - "
                f"ocx_bootstrap() builds the mirror url as <mirror>/<tag>/<filename>, so a "
                f"separator or a dot segment here walks out of the release directory. "
                f"Check {RELEASE_PAGE} against {DIST_URL}; never edit rows by hand."
            )
    filename = r.get("filename")
    if ext_of(filename) is None:
        die(
            f"{where}: filename {filename!r} has no extension ocx_bootstrap() can extract "
            f"(known: {', '.join(KNOWN_EXTS)}). Teach the module the new format first."
        )


def validate(manifest, version, required=frozenset()):
    """Dies on anything that would break ocx_bootstrap() for `version`.

    `required` is the target set the outgoing pin covers, which `version` must
    cover too. Callers run index_rows() first: duplicate (version, target)
    rows would inflate the coverage count.
    """
    # Target checks are scoped to `version` (an unconditional one false-fires
    # mid-publish); check_row() runs over every row elsewhere.
    rows = rows_for(manifest, version)
    # Coverage, not headcount: 9 rows that skip aarch64-apple-darwin clear any
    # count check. Measured against what the outgoing pin covers rather than a
    # hardcoded list, so upstream renaming a target needs an operator, not a
    # code change.
    missing = sorted(required - {r["target"] for r in rows})
    if missing:
        die(
            f"{version} has no row for {', '.join(missing)}, which the current pin covers - "
            f"the release may still be publishing (retry), or upstream dropped or renamed the "
            f"target. Check {RELEASE_PAGE} before pinning it."
        )
    # One-sided on purpose: too few rows is a release still publishing; too
    # many is upstream adding a target, a normal release that must not turn
    # `task dist:check` red repo-wide.
    if len(rows) < EXPECTED_TARGETS:
        die(
            f"expected at least {EXPECTED_TARGETS} targets for {version}, got {len(rows)} - "
            f"the release may still be publishing; retry or pass --version"
        )
    for r in rows:
        check_row(r, f"{version} {r['target']}")
    return rows


def assert_latest_stable(manifest):
    """Refuses a manifest whose "latest" pointer is not channel "stable": the
    auto-selected version must never come from a beta/rc/nightly pointer.
    Only called on the auto-select path (no explicit --version).
    """
    latest = manifest.get("latest")
    if not latest:
        # No pointer to trust; newest_stable() filters `releases` by channel.
        return
    if latest.get("channel") != "stable":
        die(
            f"{DIST_URL} 'latest' points at {latest.get('version', '?')} on channel "
            f"{latest.get('channel', '<missing>')!r}, not 'stable' - auto-select follows "
            f"that pointer. Read the ocx changelog, then pin by hand with --version <x.y.z>."
        )


def assert_forward(before, target):
    """Refuses a `target` version not strictly greater than `before`, compared
    as integer tuples, so the pin never moves backwards. Guards the
    auto-selected version only; an explicit --version bypasses it.
    """
    if version_key(target) <= version_key(before):
        die(
            f"refusing to move the pin {before} -> {target}: the snapshot's latest stable "
            f"is not newer than the current pin. Pass --version {target} to pin it anyway."
        )


def index_rows(manifest, where):
    """Indexes a manifest's releases by (version, target) after checking it is
    shaped like one. Refuses a duplicate key: a dict keeps the LAST row per
    key, but __ocx_select_release() in ocx.cmake returns the FIRST, so a
    second row would be invisible to every guard and still be what gets
    downloaded.
    """
    schema = manifest.get("schema")
    # type() because json.loads gives True for `true`, and True == 1.
    if type(schema) is not int or schema != 1:
        die(
            f"{where} declares schema {schema!r}, and ocx_bootstrap() reads schema 1 only - "
            f"teach __ocx_select_release() the new schema before embedding a manifest that uses it"
        )
    rows = manifest.get("releases")
    if not isinstance(rows, list):
        die(f"{where} has no 'releases' list ({type(rows).__name__}) - refusing to guess its shape")
    latest = manifest.get("latest")
    if latest is not None and not isinstance(latest, dict):
        die(f"{where} has a non-object 'latest' ({latest!r}) - refusing to guess its shape")
    out = {}
    for r in rows:
        if not isinstance(r, dict) or not all(isinstance(r.get(f), str) for f in ("version", "target")):
            die(f"{where} has a release row without a string version and target: {r!r}")
        key = (r["version"], r["target"])
        if key in out:
            die(
                f"{where}: {key[0]} {key[1]} appears twice - __ocx_select_release() takes the "
                f"first match, so a duplicate row shadows a committed sha256. Check "
                f"{RELEASE_PAGE}/tag/{r.get('tag', '?')} and `git log -p -- ocx.cmake` for "
                f"when it landed. Never edit rows by hand."
            )
        out[key] = r
    return out


def assert_additions_only(committed, incoming):
    """Refuses a snapshot update unless the only change is new rows. A
    (version, target) row present on both sides that differs in any field is
    a hard failure (the sha256 column is the security boundary), and so is a
    committed row absent from `incoming`. Every added row goes through
    check_row(), because validate() sees only the pinned version while the
    whole manifest gets written.
    """
    # Indexed on both sides: a duplicate that ever landed would otherwise be
    # permanently invisible, since it compares equal to itself every refresh.
    old = index_rows(committed, "the embedded snapshot")
    new = index_rows(incoming, DIST_URL)

    dropped = sorted(f"{v} {t}" for v, t in old if (v, t) not in new)
    if dropped:
        die(
            f"refusing the refresh: rows for {', '.join(dropped)} are committed in {OCX_CMAKE.name} "
            f"but absent from {DIST_URL} - a released row must not disappear. Check "
            f"{RELEASE_PAGE} for a deleted or re-cut release before anything else; "
            f"never drop rows by hand."
        )

    # Union of fields, so a column appearing upstream also trips this: a new
    # column changes what an already-committed row means.
    for key, was in old.items():
        now = new[key]
        moved = sorted(f for f in set(was) | set(now) if was.get(f) != now.get(f))
        if moved:
            fields = ", ".join(f"{f}: {was.get(f)!r} -> {now.get(f)!r}" for f in moved)
            die(
                f"refusing the refresh: {key[0]} {key[1]} was rewritten upstream ({fields}) - "
                f"a committed row is immutable, and its sha256 is what ocx_bootstrap() "
                f"enforces. Compare {RELEASE_PAGE}/tag/{was.get('tag', '?')} with the "
                f"committed row (`git show HEAD:ocx.cmake`); never edit rows by hand."
            )

    for key in sorted(set(new) - set(old)):
        check_row(new[key], f"{key[0]} {key[1]} (new in {DIST_URL})")


def _workflow_files():
    return sorted(list(WORKFLOWS.glob("*.yml")) + list(WORKFLOWS.glob("*.yaml")))


def _setup_ocx_pins(lines, name):
    """Yields (line index, regex match) for the `version:` line of every
    ocx-sh/setup-ocx step. A step whose version cannot be located is a
    die(), not a skip: a miss is otherwise indistinguishable from success
    and CI would keep running the old ocx while the snapshot and pin move.
    """
    for i, line in enumerate(lines):
        if "ocx-sh/setup-ocx@" not in line:
            continue
        for j in range(i + 1, min(i + 4, len(lines))):
            m = re.match(r'(\s*version:\s*)"([^"]+)"(.*)$', lines[j].rstrip("\r\n"))
            if m:
                yield j, m
                break
        else:
            die(
                f"{name}:{i + 1}: this setup-ocx step has no `version: \"<x.y.z>\"` in the 3 "
                f"lines below it, so the CI pin cannot be tracked - CI would keep running the "
                f"old ocx while the snapshot and __OCX_PIN_VERSION move. Quote the value and "
                f"keep it directly under `with:`, or repin this step by hand."
            )


def plan_ci_pins(version):
    """{path: new text} for every workflow whose setup-ocx pin differs from
    `version`. Computes everything first so a die() leaves no file half-moved.
    """
    plan = {}
    for wf in _workflow_files():
        lines = read(wf).splitlines(keepends=True)
        hits = 0
        for j, m in _setup_ocx_pins(lines, wf.name):
            if m.group(2) != version:
                body = lines[j].rstrip("\r\n")
                eol = lines[j][len(body) :]  # preserve the line ending verbatim
                lines[j] = f'{m.group(1)}"{version}"{m.group(3)}{eol}'
                hits += 1
        if hits:
            plan[wf] = ("".join(lines), hits)
    return plan


def assert_ci_in_lockstep(pin):
    """--check: every setup-ocx pin equals the module pin."""
    for wf in _workflow_files():
        lines = read(wf).splitlines(keepends=True)
        for j, m in _setup_ocx_pins(lines, wf.name):
            if m.group(2) != pin:
                die(
                    f"{wf.name}:{j + 1}: setup-ocx pins ocx {m.group(2)} but __OCX_PIN_VERSION is "
                    f"{pin} - run `task dist:update`, which moves both together."
                )


def main():
    ap = argparse.ArgumentParser(
        description="Bump the ocx CLI snapshot, pin and CI pins in lockstep.",
    )
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument(
        "--version",
        help="exact ocx version to pin (default: the manifest's latest stable). "
        "Bypasses the auto-select guards (forward-only, 'latest' channel); the "
        "per-row and additions-only checks still apply",
    )
    mode.add_argument(
        "--check",
        action="store_true",
        help="validate the embedded snapshot and the CI pins against the module pin; write nothing",
    )
    mode.add_argument(
        "--snapshot-only",
        action="store_true",
        help="refresh the embedded snapshot only (additions-only checked); pin and CI pins untouched",
    )
    args = ap.parse_args()

    text = read(OCX_CMAKE)
    before = pin_of(text)
    committed = embedded_snapshot(text)

    if args.check:
        # index_rows() for a duplicate row hand-landed in the snapshot, then
        # check_row() over every committed row: only the target count is
        # scoped to the pin. A hand-edited row for a version nobody pins is
        # still a url+sha256 pair ocx_bootstrap(VERSION ...) can select.
        indexed = index_rows(committed, "the embedded snapshot")
        for (version, target), r in sorted(indexed.items()):
            check_row(r, f"{version} {target}")
        rows = validate(committed, before)
        assert_ci_in_lockstep(before)
        exts = sorted({ext_of(r["filename"]) for r in rows})
        print(f"OK: {before} x {len(rows)} targets, archives {exts}; {len(indexed)} rows checked")
        return

    body, manifest = fetch_snapshot()

    # Guards first: nothing is written until every one of them passes.
    assert_additions_only(committed, manifest)
    if args.snapshot_only:
        version = before  # a refresh, not a bump
    elif args.version:
        version = args.version
    else:
        assert_latest_stable(manifest)
        version = newest_stable(manifest)
        if version != before:
            assert_forward(before, version)
    # `before` is read from the committed snapshot, so upstream cannot shrink
    # the set the new pin is measured against.
    rows = validate(manifest, version, {r["target"] for r in rows_for(committed, before)})
    ci_plan = {} if args.snapshot_only else plan_ci_pins(version)

    old_exts = sorted({ext_of(r["filename"]) for r in rows_for(manifest, before)}) if before != version else []
    new_exts = sorted({ext_of(r["filename"]) for r in rows})

    new_text = splice_snapshot(text, body)
    if not args.snapshot_only:
        new_text = set_pin(new_text, version)
    write(OCX_CMAKE, new_text)
    for wf, (wf_text, _hits) in ci_plan.items():
        write(wf, wf_text)

    print(f"snapshot: {OCX_CMAKE.name} refreshed from {DIST_URL}")
    print(f"pin:      {before} -> {version}" if version != before else f"pin:      {version} (unchanged)")
    if args.snapshot_only:
        print("ci pins:  untouched (--snapshot-only)")
    else:
        moved = ", ".join(f"{wf.name} ({hits})" for wf, (_t, hits) in ci_plan.items())
        print(f"ci pins:  {moved}" if moved else "ci pins:  already current")
    print(f"targets:  {len(rows)}, archives {new_exts}")
    if old_exts and old_exts != new_exts:
        print(
            f"\nNOTE: archive format changed {old_exts} -> {new_exts}. Confirm "
            f"ocx_bootstrap() extracts every new extension and layout "
            f"(tests/i1.cmake covers .tar.gz and .zip)."
        )


if __name__ == "__main__":
    main()
